nameofapp/config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}
  resources :users

  resources :products

  get 'static_pages/contact'

  get 'static_pages/about'

  get 'static_pages/index'

   root 'static_pages#landing_page'

  resources :orders, only: [:index, :show, :create, :destroy]
  
  post 'static_pages/thank_you'

end

nameofapp/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    can :manage, User, id: user.id
  end
end

nameofapp/app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :product
  belongs_to :user
end

nameofapp/app/models/product.rb
class Product < ActiveRecord::Base
  has_many :orders
end

nameofapp/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :orders
end

nameofapp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
    rescue_from CanCan::AccessDenied do |exception|
    redirect_to main_app.root_url, :alert => exception.message
  end
end

nameofapp/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  
  before_filter :authenticate_user!
  
  def index
  end
  
  def show
  end
  
  def new
  end
  
  def create
  end
  
  def destroy
  end
  
end

nameofapp/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    if params[:q]
      search_term = params[:q]
      if Rails.env.development?
        @products = Product.where("name LIKE ?", "%#{search_term}%")
      else
        @products = Product.where("name iLIKE ?", "%#{search_term}%")
      end
      # return our filterd list here
    else
      @products = Product.all
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :image_url, :colour, :price)
    end
end

nameofapp/app/controllers/static_controller.rb
class StaticController < ApplicationController
end

nameofapp/app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about
  end
  
  def landing_page
    @products = Product.limit(3)
    @featured_product = Product.first
  end
  
  def thank_you
    @name = params[:name]
    @email = params[:email]
    @message = params[:message]
    UserMailer.contact_form(@email, @name, @message).deliver
  end
end

nameofapp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name)
    end
end

nameofapp/app/helpers/application_helper.rb
module ApplicationHelper
end

nameofapp/app/helpers/products_helper.rb
module ProductsHelper
end

nameofapp/app/helpers/static_helper.rb
module StaticHelper
end

nameofapp/app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

nameofapp/app/helpers/users_helper.rb
module UsersHelper
end

nameofapp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Okanagan Wood Rings</title>
  
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  
  <link href="https://fonts.googleapis.com/css?family=Roboto+Condensed" rel="stylesheet">
  
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
  
<body>
<body data-spy="scroll" data-target=".navbar">
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <div class="WoodRings navbar-brand">
          <a href="#">OKWoodRings</a>
        </div>
        <!--end WoodRings -->
      </div>
      <!--end navbar-header -->
      <div class="navbar-collapse collapse">
        <%= form_tag("/products", class:"navbar-form navbar-left", role:"search", method:"get") do %>
          <%= content_tag(:div, text_field_tag('q', nil, class:"form-control", placeholder:"Enter search term..."), class:"form-group") %>
            <%= submit_tag("Search", class:"btn btn-default") %>
        <% end %>

        <ul class="nav navbar-nav navbar-right">
          <li><a href="/">Home</a></li>
          <li><%= link_to "About", static_pages_about_path %></li>
          <li><%= link_to "Contact", static_pages_contact_path %></li>
          <li><%= link_to "Products", products_path %></li>
        </ul>
        <ul class="nav navbar-nav pull-right">
          <li>
          <% if user_signed_in? %>
            <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
          <% else %>
            <%= link_to('Login', new_user_session_path) %>
          <% end %>
          </li>
        </ul>
      </div>
      <!-- nav -->
    </div>
    <!-- end nav container-->
  </nav>
    <!-- end navbar-->
  <div class="page-wrap">
    <% if notice %>
      <p id="notice" class="alert alert-info"><%= notice %></p>
    <% end %>   
    <% if alert %>
      <p id="alert" class="alert alert-danger"><%= alert %></p>
    <% end %> 

    <%= yield %>
  </div>
  <footer class="site-footer">
    &copy; 2016 Okanagan Wood Rings
  </footer>
</body>
</html>

nameofapp/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :colour %><br>
    <%= f.text_field :colour %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

nameofapp/app/views/products/_product.html.erb
<div class = "col-xs-12 col-md-4">
 
      <h2>
        <%= product.name %>
      </h2>
      <%= image_tag(product.image_url, class: "img-responsive") %>
      <p>
        <strong>Description:</strong>
        <%= product.description %>
      </p>
      <p>
        <strong>Colour:</strong>
        <%= product.colour %>
      </p>
      <p>
        <strong>Price(CAD):</strong>
        $<%= product.price %>0
      </p>
    <%= link_to 'Show', product %> |
    <%= link_to 'Edit', edit_product_path(product) %> |
    <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
    </div><!--end col-->

nameofapp/app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

nameofapp/app/views/products/index.html.erb
<h1>Listing products</h1>

<div class = "container-fluid">
  <div class = "row">    
     <%= render partial: "product", collection: @products %> 
  </div><!--end row-->  

<br>
<%= link_to 'New Product', new_product_path %>
</div> <!--end container-->

nameofapp/app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

nameofapp/app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<div class = "container">
  <div class="row">
    <div class="col-md-6 col-xs-12">
      <div class = "prodinfo">
        <p>
          <strong>Name:</strong>
          <%= @product.name %>
        </p>

        <p>
          <strong>Description:</strong>
          <%= @product.description %>
        </p>
        <p>
          <strong>Colour:</strong>
          <%= @product.colour %>
        </p>
         <p>
          <strong>Price:</strong>
          $<%= @product.price %>0
        </p>
      </div><!--end prodinfo-->
    </div><!--end col-->
    <div class="col-md-6 col-xs-12">
        <div class = "prodimg">
          <%= image_tag(@product.image_url, class: "img-responsive") %>
        </div><!--end prodimg-->    
    </div><!--end col-->
  </div>
  <%= link_to 'Edit', edit_product_path(@product) %> |
  <%= link_to 'Back', products_path %>
</div><!--end container-->

nameofapp/app/views/static_pages/about.html.erb
<div class = "container">
  <h1>About</h1>
	<div class="row">
		<div class="col-md-6 col-xs-12">  
      <%= image_tag("papa.jpg", class: "img-responsive")%>
    </div><!--end col-->
    <div class="col-md-6 col-xs-12">
      <div class= "aboutinfo">
        <p>My grandpa is a fixit kind of guy, a total handyman. After doing a number of home renovations he had a bunch of wood left over. Some hard wood flooring, and some general scrap
  so he decided to start making rings with it. After all our family had one ring per finger and toe, he decided to branch out making them for friends, aquaintances, neighbours and strangers.
        </p>
        <p>
   My grandpa likes making them and he's run out of people to make them for. We hope you like them. 
       </p>
      </div>
    </div>
  </div><!--end row-->
</div>

nameofapp/app/views/static_pages/contact.html.erb
<div class="container">
  <h1>Contact Us</h1>

  <%= flash[:notice] %>

  <%= form_tag("/static_pages/thank_you") do %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= label_tag :name %>
        <%= text_field_tag :name, nil, class: "form-control", placeholder: "Enter Name" %>
      </div>      
      <div class="form-group">
        <%= label_tag :email, "Email Address" %>
        <%= text_field_tag :email, nil, class: "form-control", placeholder: "Enter Email" %>
      </div>
      <div class="form-group">
        <%= label_tag :message %>
        <%= text_area_tag :message, nil, class: "form-control", placeholder: "Enter Message" %>
      </div>      
    </div>
  </div>
  <%= submit_tag "Send", class:"btn btn-default" %>  
  <% end %>
</div>

nameofapp/app/views/static_pages/index.html.erb
<h1>Welcome to Okanagan Wood Rings</h1>
<h2>
 Your source for handcrafted wood rings. 
</h2>
<div class = "homepic">
  <%= image_tag("mahogany1.jpg")%>
</div>
  

nameofapp/app/views/static_pages/landing_page.html.erb
<h1>
  Okanagan Wood Rings
</h1>

<h2>
  Featured Products
</h2>
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <% @products.each do |p, i| %>
      <li data-target="#image-carousel" data-slide-to="#{i}" class="#{'active' if i == 0}"></li>
    <% end %>
  </ol>
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <% @products.each do |product| %>
    <div class="item<%= " active" if product == @products.first %>">
      <%= image_tag(product.image_url) %>
      <div class="carousel-caption">
        <%= product.name %>
      </div>
    </div>
    <% end %>
  <!-- Controls -->
  <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

nameofapp/app/views/static_pages/thank_you.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <p>Thank you. We have received your message and will respond as soon as possible.</p>
  </div><!-- / panel-body -->
</div><!-- / panel -->

nameofapp/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

nameofapp/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

nameofapp/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

nameofapp/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

nameofapp/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @user.last_name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>